topics:
  - name: ffc-pay-request
    subscriptions:
      - ffc-pay-enrichment
  - name: ffc-pay-request-response
  - name: ffc-pay-processing
    subscriptions:
      - ffc-pay-processing
  - name: ffc-pay-submit
    subscriptions:
      - ffc-pay-submission
  - name: ffc-pay-acknowledge
    subscriptions:
      - ffc-pay-processing
  - name: ffc-pay-return
    subscriptions:
      - ffc-pay-processing
  - name: ffc-pay-debt-data
    subscriptions:
      - ffc-pay-processing
  - name: ffc-pay-quality-check
    subscriptions:
      - ffc-pay-request-editor
  - name: ffc-pay-request-edit
    subscriptions:
      - ffc-pay-processing
  - name: ffc-pay-statement-data
    subscriptions:
      - ffc-pay-statements
