topics:
  - name: ffc-pay-request
    subscriptions:
      - ffc-pay-enrichment
  - name: ffc-pay-request-response
  - name: ffc-pay-processing
    subscriptions:
      - ffc-pay-processing
  - name: ffc-pay-submit
    subscriptions:
      - ffc-pay-submission
  - name: ffc-pay-acknowledge
    subscriptions:
      - ffc-pay-processing
  - name: ffc-pay-return
    subscriptions:
      - ffc-pay-processing
  - name: ffc-pay-debt-data
    subscriptions:
      - ffc-pay-request-editor
  - name: ffc-pay-debt-data-response
    subscriptions:
      - ffc-pay-processing
  - name: ffc-pay-manual-check-data
    subscriptions:
      - ffc-pay-request-editor
  - name: ffc-pay-quality-check
    subscriptions:
      - ffc-pay-processing
  - name: ffc-pay-file-send
    subscriptions:
      - ffc-pay-file-sender
  - name: ffc-pay-file-consume
    subscriptions:
      - ffc-pay-file-consumer
  - name: ffc-pay-event
    subscriptions:
      - ffc-pay-event
  - name: ffc-pay-event-projection
    subscriptions:
      - ffc-pay-event-projection
