topics:
  - name: ffc-pay-request
    subscriptions:
      - ffc-pay-enrichment
  - name: ffc-pay-processing
    subscriptions:
      - ffc-pay-processing
  - name: ffc-pay-submit
    subscriptions:
      - ffc-pay-submission
  - name: ffc-pay-acknowledge
    subscriptions:
      - ffc-pay-processing
  - name: ffc-pay-return
    subscriptions:
      - ffc-pay-processing
