topics:
  - name: ffc-sfd-messages
    subscriptions:
      - ffc-sfd-messages-processor
  - name: ffc-sfd-customer
    subscriptions:
      - ffc-sfd-customer-receiver-messages
  - name: ffc-sfd-customer-applications
    subscriptions:
      - ffc-sfd-customer-receiver-applications  
  - name: ffc-sfd-customer-payments
    subscriptions:
      - ffc-sfd-customer-receiver-payments  
queues:
  - name: ffc-sfd-backend
