topics:
  - name: ffc-sfi-eligibility-check
    subscriptions:
      - ffc-sfi-eligibility-check-calculator
  - name: ffc-sfi-parcel-spatial-request
    subscriptions:
      - ffc-sfi-parcel-spatial-request-calculator
  - name: ffc-sfi-standards-request
    subscriptions:
      - ffc-sfi-standards-request-calculator
  - name: ffc-sfi-parcel-standard-request
    subscriptions:
      - ffc-sfi-parcel-standard-request-calculator
  - name: ffc-sfi-agreement-calculate
    subscriptions:
      - ffc-sfi-agreement-calculate-calculator
  - name: ffc-sfi-agreement-submit
    subscriptions:
      - ffc-sfi-agreement-submit-calculator
      - ffc-sfi-agreement-submit-processing
  - name: ffc-sfi-agreement-withdraw
    subscriptions:
      - ffc-sfi-agreement-withdraw-calculator
  - name: ffc-sfi-agreement-validate
    subscriptions:
      - ffc-sfi-agreement-validate-calculator
  - name: ffc-sfi-agreement-validate-response
    subscriptions:
      - ffc-sfi-agreement-validate-response-processing
      - ffc-sfi-agreement-validate-response-crm
  - name: ffc-sfi-crm-case
  - name: ffc-sfi-crm-close
    subscriptions:
      - ffc-sfi-crm-close-processing
  - name: ffc-sfi-agreement-case
    subscriptions:
      - ffc-sfi-agreement-case-processing
  - name: ffc-sfi-crm-case-closed
    subscriptions:
      - ffc-sfi-crm-case-closed-processing
  - name: ffc-sfi-crm-case-create
    subscriptions:
    - ffc-sfi-crm-case-create-crm
    - ffc-sfi-crm-case-closed-processing
queues:
  - name: ffc-sfi-eligibility-check-response
    sessions: true
  - name: ffc-sfi-parcel-spatial-response
    sessions: true
  - name: ffc-sfi-standards-request-response
    sessions: true
  - name: ffc-sfi-parcel-standard-response
    sessions: true
  - name: ffc-sfi-agreement-calculate-response
    sessions: true
  - name: ffc-sfi-agreement-validation
    sessions: true
