topics:
  - name: ffc-pay-request
    subscriptions:
      - ffc-pay-enrichment
  - name: ffc-pay-request-response
    subscriptions:
      - ffc-pay-tracking
  - name: ffc-pay-processing
    subscriptions:
      - ffc-pay-processing
      - ffc-pay-statement-constructor
      - ffc-pay-tracking
  - name: ffc-pay-submit
    subscriptions:
      - ffc-pay-submission
      - ffc-pay-responses
      - ffc-pay-statement-constructor
      - ffc-pay-tracking
  - name: ffc-pay-acknowledgement
    subscriptions:
      - ffc-pay-processing
      - ffc-pay-tracking
  - name: ffc-pay-return
    subscriptions:
      - ffc-pay-processing
      - ffc-pay-statement-constructor
      - ffc-pay-tracking
  - name: ffc-pay-debt-data
    subscriptions:
      - ffc-pay-request-editor
  - name: ffc-pay-debt-data-response
    subscriptions:
      - ffc-pay-processing
  - name: ffc-pay-manual-check-data
    subscriptions:
      - ffc-pay-request-editor
  - name: ffc-pay-quality-check
    subscriptions:
      - ffc-pay-processing
  - name: ffc-pay-file-send
    subscriptions:
      - ffc-pay-file-sender
      - ffc-pay-file-publisher
  - name: ffc-pay-file-consume
    subscriptions:
      - ffc-pay-file-consumer
  - name: ffc-pay-events
    subscriptions:
      - ffc-pay-event-hub
  - name: ffc-pay-alert
    subscriptions:
      - ffc-pay-alerting
  - name: ffc-pay-data-request
    subscriptions:
      - ffc-pay-data-hub
queues:
  - name: ffc-pay-data-request-response
    sessions: true
