topics:
  - name: ffc-sfd-messages
    subscriptions:
      - ffc-sfd-messages-processor
  - name: ffc-sfd-customer-receiver
    subscriptions:
      - ffc-sfd-customer-receiver-messages
queues:
  - name: ffc-sfd-backend
